#!/usr/bin/env python3
"""
mcp_trading_server.py - MCP server local para Claude Desktop

Expone las decisiones del Slot 6 y el estado de cartera como herramientas
que Claude Desktop puede usar junto con la integración IBKR.

Versión: 1.0.0
Fecha: 26/06/2026
"""

import json
import asyncio
from datetime import datetime
from pathlib import Path

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp import types

BASE = Path(__file__).parent
DECISIONES_FILE = BASE / "data" / "decisiones_claude.json"
ESTADO_FILE     = BASE / "data" / "estado_ibkr_sync.json"

server = Server("trading-slot6")


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(
            name="get_slot6_orders",
            description=(
                "Returns today's Slot 6 buy/sell orders for the IBKR-UK Real account. "
                "Use this to get the orders to place in IBKR."
            ),
            inputSchema={"type": "object", "properties": {}, "required": []}
        ),
        types.Tool(
            name="get_portfolio",
            description=(
                "Returns current positions and available cash in the IBKR-UK Real account "
                "as last synced via Flex Web Service."
            ),
            inputSchema={"type": "object", "properties": {}, "required": []}
        ),
    ]


@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list[types.TextContent]:
    if name == "get_slot6_orders":
        return [types.TextContent(type="text", text=_get_slot6_orders())]
    elif name == "get_portfolio":
        return [types.TextContent(type="text", text=_get_portfolio())]
    else:
        return [types.TextContent(type="text", text=f"Unknown tool: {name}")]


def _get_slot6_orders() -> str:
    if not DECISIONES_FILE.exists():
        return "No decisions file found."

    with open(DECISIONES_FILE, encoding="utf-8") as f:
        data = json.load(f)

    hoy = datetime.now().strftime("%Y-%m-%d")
    ordenes = []

    for entrada in data.get("decisiones", []):
        if not isinstance(entrada, dict):
            continue
        fecha = entrada.get("fecha_analisis", entrada.get("fecha", ""))
        if not fecha.startswith(hoy):
            continue
        if entrada.get("plataforma") != "IBKR-UK" or entrada.get("modo") != "Real":
            continue

        for t in entrada.get("decisiones_tickers", []):
            ticker  = t.get("ticker", "")
            accion  = t.get("accion", "esperar")
            cant_c  = t.get("cantidad_compra", 0) or 0
            cant_v  = t.get("cantidad_venta", 0) or 0
            precio_c = t.get("precio_compra_sugerido")
            precio_v = t.get("precio_venta_sugerido")

            if accion in ("comprar", "comprar y vender") and cant_c > 0 and precio_c:
                ordenes.append(f"BUY {cant_c} {ticker} at ${precio_c:.2f} (limit)")
            if accion in ("vender", "comprar y vender") and cant_v > 0 and precio_v:
                ordenes.append(f"SELL {cant_v} {ticker} at ${precio_v:.2f} (limit)")

    if not ordenes:
        return f"No buy/sell orders for IBKR-UK Real today ({hoy}). All tickers are HOLD."

    lines = [f"Slot 6 orders for IBKR-UK Real — {hoy}:", ""]
    lines += ordenes
    lines += ["", "These are limit orders generated by the Slot 6 analysis system."]
    return "\n".join(lines)


def _get_portfolio() -> str:
    historial_file = BASE / "data" / "historial_operaciones.json"
    if not historial_file.exists():
        return "No historial_operaciones.json found."

    with open(historial_file, encoding="utf-8") as f:
        data = json.load(f)

    sync = data.get("config_plataformas", {}).get("IBKR-UK", {}).get("ultimo_sync_real", {})
    if not sync:
        return "No IBKR-UK Real sync data found in historial_operaciones.json."

    fecha   = sync.get("fecha", "unknown")
    capital = sync.get("capital", "unknown")
    pos     = sync.get("posiciones", {})

    lines = [
        f"IBKR-UK Real portfolio (synced: {fecha})",
        f"Available cash: {capital}",
        "",
        "Positions:",
    ]
    if pos:
        for ticker, qty in sorted(pos.items()):
            lines.append(f"  {ticker}: {qty} shares")
    else:
        lines.append("  (no open positions)")

    return "\n".join(lines)


async def main():
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options()
        )


if __name__ == "__main__":
    asyncio.run(main())
